"use client";

import { useState } from "react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { PlusCircle, Activity } from "lucide-react";

import { SchedulesTable } from "./components/SchedulesTable";
import { WorkOrdersTable } from "./components/WorkOrdersTable";
import { AddScheduleModal } from "./components/AddScheduleModal";
import { LogUsageModal } from "./components/LogUsageModal";

import {
  useGetSchedules,
  useGetWorkOrders,
  useCompleteWorkOrder,
} from "./hooks/usePreventiveMaintenance";

export default function PreventiveMaintenanceModule() {
  const [activeTab, setActiveTab] = useState<string>("schedules");
  const [isAddScheduleModalOpen, setIsAddScheduleModalOpen] = useState(false);
  const [isLogUsageModalOpen, setIsLogUsageModalOpen] = useState(false);

  const {
    data: schedules,
    isLoading: isLoadingSchedules,
    refetch: refetchSchedules,
  } = useGetSchedules();

  const {
    data: workOrders,
    isLoading: isLoadingWorkOrders,
    refetch: refetchWorkOrders,
  } = useGetWorkOrders();

  const { mutateAsync: completeWorkOrder, isPending: isCompleting } = useCompleteWorkOrder(() => {
    refetchWorkOrders();
  });

  const handleCompleteWorkOrder = async (id: string) => {
    try {
      await completeWorkOrder({ id });
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Preventive Maintenance</h1>
          <p className="text-muted-foreground">Manage proactive maintenance schedules and view automated work orders.</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => setIsLogUsageModalOpen(true)}>
            <Activity className="mr-2 h-4 w-4" /> Log Usage
          </Button>
          <Button onClick={() => setIsAddScheduleModalOpen(true)}>
            <PlusCircle className="mr-2 h-4 w-4" /> Add Schedule
          </Button>
        </div>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-4">
        <TabsList>
          <TabsTrigger value="schedules">Active Schedules</TabsTrigger>
          <TabsTrigger value="work-orders">Work Orders</TabsTrigger>
        </TabsList>
        <TabsContent value="schedules" className="space-y-4">
          <SchedulesTable schedules={schedules} isLoading={isLoadingSchedules} />
        </TabsContent>
        <TabsContent value="work-orders" className="space-y-4">
          <WorkOrdersTable 
            workOrders={workOrders} 
            isLoading={isLoadingWorkOrders} 
            onComplete={handleCompleteWorkOrder}
            isCompleting={isCompleting}
          />
        </TabsContent>
      </Tabs>

      <AddScheduleModal
        isOpen={isAddScheduleModalOpen}
        onClose={() => setIsAddScheduleModalOpen(false)}
        onSuccess={() => refetchSchedules()}
      />
      
      <LogUsageModal
        isOpen={isLogUsageModalOpen}
        onClose={() => setIsLogUsageModalOpen(false)}
        onSuccess={() => {
          // Log usage might trigger a new work order to be generated by directus flow
          refetchWorkOrders();
        }}
      />
    </div>
  );
}
